name = "kuba"
compatibility_date = "2022-05-11"

[vars]
API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlhdCI6MTYzMDA3MjI1MiwiZXhwIjoxOTQ1NjQ4MjUyfQ.qAPu3W_iYO085QTDhZTMoz-lCFovfJcstEAki9l1_ps"
API_URL = "https://wbfsnickkamdoyzndmec.supabase.co"
