name: Deploy

on:
  push:
    branches: [ master ]
    
jobs:
  default:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install
      run: npm install
    
    - name: Test
      run: ./node_modules/.bin/cypress run

    - name: Build
      run: ./node_modules/.bin/webpack --config webpack.prod.js

    - name: Deploy
      run: ./node_modules/.bin/firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
