name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install
      run: npm install

    - name: Build
      run: webpack --config webpack.prod.js

    - name: Deploy
      run: firebase deploy --token "1//0h6_tG6E2wVpyCgYIARAAGBESNwF-L9IryzWebtIlSH8vIirxEgWXA98QCNh1HFRSOymV2Dp5TUXpdn7rdk3C3P1w6JIo5_x2rgo"
