name: Deploy

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install
      run: |
        npm install
        npm install -g cypress
        npm install -g webpack
        npm install -g firebase-tools
    
    - name: Test
      run: cypress run

    - name: Build
      run: webpack --config webpack.prod.js

    - name: Deploy
      run: firebase deploy --token "$FIREBASE_TOKEN"
