name: Worker

on:
  push:
    branches: [ master ]

    paths:
      - '.github/**'
      - 'actions/**'
      - 'blocks/**'
      - 'buckets/worker/**'
      - 'development/**'
      - 'directives/**'
      - 'elements/**'
      - 'filters/**'
      - 'infra/**'
      - 'models/**'
      - 'modules/**'
      - 'pages/**'
      - 'pixels/**'
      - 'providers/**'
      - 'standard/**'

jobs:
  deploy:
    runs-on: Ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Run yarn install
      run: |
        yarn install
        yarn global add wrangler

    - name: Run worker deploy
      env:
        API_KEY: ${{ secrets.API_KEY }}
        API_URL: ${{ secrets.API_URL }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      run: yarn workspace @kuba/worker deploy
